### ISSUE TITLE
Fatal error on return URL

### ISSUE THREAD

**Issue by ierpe** [SlimPay/woocommerce#1]
Hi,

After successfully registering a mandate on the SlimPay interface, when I am redirected on the return URL of my site, I get the following 500 error :

PHP Fatal error:  Uncaught exception 'Exception' with message 'Internal error (100)' in /my_srv_path/www.bice.org/web/app/plugins/woocommerce-gateway-slimpay/includes/class-wc-gateway-slimpay.php:526 
Stack trace:
#0 /my_srv_path/www.bice.org/web/app/plugins/woocommerce-gateway-slimpay/includes/class-wc-gateway-slimpay.php(322) : WC_Gateway_SlimPay->create_direct_debit('SLMP003819212', 10, 'order_16925')
#1 /my_srv_path/www.bice.org/web/app/plugins/woocommerce-gateway-slimpay/includes/class-wc-gateway-slimpay.php(287) : WC_Gateway_SlimPay->process_order_payment(Object(WC_Order), 'SLMP003819212')
#2 [internal function]: WC_Gateway_SlimPay->return_url('')
#3 /my_srv_path/www.bice.org/web/wp/wp-includes/plugin.php(525) : call_user_func_array(Array, Array)
#4 /my_srv_path/www.bice.org/web/app/plugins/woocommerce/includes/class-wc-api.php(321) : do_action('woocommerce_api...')
#5 [internal function]: WC_API->handle_api_requests(Object(WP))
#6 /my_srv_path/www.bice.org/web/wp/wp-includes/plugin.php(601  in /my_srv_path/www.bice.org/web/app/plugins/woocommerce-gateway-slimpay/includes/class-wc-gateway-slimpay.php  on line 526

**Comment by YoussefBO** [comment]
Hey there,

I was about to advise you to contact our support team but It seems like you already did ;)

Issues opened directly from this repository should concern technical issues or suggestions about the plugin itself. At first sight, it is not the case of this error.

Closing the issue... Thank you for your comprehension.
